version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: devboot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:
